name: Build-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master

stages:
- stage: Build
  displayName: Build PowerShell Package
  jobs:
  - job: BuildPkg
    displayName: Build Package
    pool:
      vmImage: windows-latest
    steps:
    - pwsh: |
        Install-module Pester -Force -MaximumVersion 4.99
      displayName: Install dependencies - Pester
      timeoutInMinutes: 10

    - pwsh: |
        Install-Module -Name "platyPS" -Force
      displayName: Install dependencies - PlatyPS
      timeoutInMinutes: 10

    - pwsh: |
        Install-Module -Name "PSScriptAnalyzer" -RequiredVersion 1.18.0 -Force
      displayName: Install PSScriptAnalyzer
      timeoutInMinutes: 10

    - pwsh: |
        Import-Module $env:BUILD_SOURCESDIRECTORY/src/PSPackageProject.psd1 -Force
      displayName: Install PSPackageProject module
      timeoutInMinutes: 10

    - pwsh: |
        Import-Module PowerShellGet -RequiredVersion 3.0.0-beta8 -AllowPrerelease -Force
      displayName: Install PowerShellGet V3
      timeoutInMinutes: 10

    - pwsh: |
        Get-Module -ListAvailable Pester, platyPS, PowerShellGet, PackageManagement
      displayName: List installed Modules
      timeoutInMinutes: 10

    - pwsh: |
        Install-Module -Name PSPackageProject -Force
        $config = Get-PSPackageProjectConfiguration
        $psd1Path = Join-Path -path $config.SourcePath -ChildPath "$($config.ModuleName).psd1"
        Update-ModuleManifest -path $psd1Path -ModuleVersion $config.Version
      displayName: Update Version
      timeoutInMinutes: 10

    - pwsh: |
        Import-Module $env:BUILD_SOURCESDIRECTORY/src/PSPackageProject.psd1 -Force
        $(Build.SourcesDirectory)/build.ps1 -Build
      displayName: Build
      timeoutInMinutes: 10

    - pwsh: |
        Write-Verbose "BUILD_OUTPUT_PATH- $env:BUILD_OUTPUT_PATH" -Verbose
        Write-Verbose "SIGNED_OUTPUT_PATH- $env:SIGNED_OUTPUT_PATH" -Verbose
        Copy-Item $env:BUILD_OUTPUT_PATH $env:SIGNED_OUTPUT_PATH -Recurse -Force
      displayName: Build Signing Placeholder
      timeoutInMinutes: 10

    - pwsh: |
        Install-Module -Name PSPackageProject -Force
        $config = Get-PSPackageProjectConfiguration
        $(Build.SourcesDirectory)/package.ps1 -Version $config.Version -OutputDirectory '$(System.ArtifactsDirectory)'
        # $(Build.SourcesDirectory)/build.ps1 -Publish -Signed
      displayName: Publish
      timeoutInMinutes: 10

    - pwsh: |
        dir '$(System.ArtifactsDirectory)' -Recurse
      displayName: capture ArtifactsDirectory
      timeoutInMinutes: 10

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.ArtifactsDirectory)'
        artifactName: 'nupkg'

- stage: Test
  displayName: Test Package
  jobs:
  - template: test.yml
    parameters:
      jobName: TestPkgWin
      displayName: PowerShell Core on Windows
      imageName: windows-2019

  - template: test.yml
    parameters:
      jobName: TestPkgWinPS
      displayName: Windows PowerShell on Windows
      imageName: windows-2019
      powershellExecutable: powershell

  - template: test.yml
    parameters:
      jobName: TestPkgUbuntu16
      displayName: PowerShell Core on Ubuntu 16.04
      imageName: ubuntu-16.04

  - template: test.yml
    parameters:
      jobName: TestPkgWinMacOS
      displayName: PowerShell Core on macOS
      imageName: macOS-10.14

- stage: Release
  displayName: Release Package
  # add `succeeded(),` to the and statement
  condition: and( eq(variables['Build.Reason'], 'Manual'), eq(variables['Publish'], 'Yes'))
  jobs:
  - template: release.yml
