parameters:
  jobName: TestPkgWin
  imageName: windows-2019
  displayName: PowerShell Core on Windows
  powershellExecutable: pwsh

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}
  steps:
  - ${{ parameters.powershellExecutable }}: |
        Install-Module -Name "PSScriptAnalyzer","platyPS","Pester" -Force
    displayName: Install dependencies
  - ${{ parameters.powershellExecutable }}: |
      Import-Module $env:BUILD_SOURCESDIRECTORY/src/PSPackageProject.psd1 -Force
    displayName: Install PSPackageProject module
  - ${{ parameters.powershellExecutable }}: |
      Import-Module $env:BUILD_SOURCESDIRECTORY/src/PSPackageProject.psd1 -Force
      Invoke-PSPackageProjectTest -Type Functional
    displayName: Execute functional tests
  - ${{ parameters.powershellExecutable }}: |
      Import-Module $env:BUILD_SOURCESDIRECTORY/src/PSPackageProject.psd1 -Force
      Invoke-PSPackageProjectTest -Type StaticAnalysis
    displayName: Execute static analysis tests
