parameters:
  jobName: TestPkgWin
  imageName: windows-2019
  displayName: PowerShell Core on Windows
  powershellExecutable: pwsh

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}
  steps:
  - ${{ parameters.powershellExecutable }}: |
        Install-Module -Name "PSScriptAnalyzer","platyPS","Pester" -Force
    displayName: Install dependencies

  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: single
      artifactName: NuPkg
      downloadPath: '$(System.ArtifactsDirectory)'

  - ${{ parameters.powershellExecutable }}: |
      $sourceName = 'pspackageproject-local-repo'
      $buildOutputPath = (Get-PSPackageProjectConfig).BuildOutputPath
      $null = New-Item -ItemType Directory -Path $buildOutputPath -Verbose
      Register-PSRepository -Name $sourceName -SourceLocation '$(System.ArtifactsDirectory)' -ErrorAction Ignore
    displayName: Extract product artifact

  - ${{ parameters.powershellExecutable }}: |
      Install-Module -Name PSPackageProject -Force -Repository 'pspackageproject-local-repo'
      Invoke-PSPackageProjectTest -Type Functional
    displayName: Execute functional tests

  - ${{ parameters.powershellExecutable }}: |
      Install-Module -Name PSPackageProject -Force -Repository 'pspackageproject-local-repo'
      Invoke-PSPackageProjectTest -Type StaticAnalysis
    displayName: Execute static analysis tests

  - ${{ parameters.powershellExecutable }}: |
      Unregister-PSRepository -Name 'pspackageproject-local-repo' -ErrorAction Ignore
    displayName: Unregister temporary PSRepository
